# Add C++ Preprocessor
env = Environment(CPPFLAGS='-D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DVERSION=\\\"1.0.0.0\\\" -DDEBUG')

# Add C compile-time flags
env.Append(CCFLAGS='-g -pipe -W -Wall')

#env.Append(CXXFLAGS='-g -pipe -W -Wall')

# Add header search path
env.Append(CPPPATH = ['../include/mysql'])

# Add library search path
env.Append(LIBPATH = ['../lib/mysql'])

# Add libraries to link against
env.Append(LIBS = ['mysqlclient', 'z'])

# Add define
#env.Append(CPPDEFINES=['BIG_ENDIAN'])
# add define with value (e.g. -DRELEASE_BUILD=1)
#env.Append(CPPDEFINES={'RELEASE_BUILD' : '1'})

# Link time flags
#env.Append(LINKFLAGS = ['-lpthread -lcrypto -lrt'])

t1 = env.Program(target='mysql_timeout_ms_test', source=['mysql_timeout_ms_test.cpp'])
Default(t1)

